### ISSUE TITLE
問診終了時にエラーになる場合がある

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#100]
再現条件がわかりませんので、備忘録として画面コピーを添付しておきます。
最初からやり直すとうまくいく。

![default](https://cloud.githubusercontent.com/assets/24665918/22089651/f3a7f5be-de2f-11e6-8adc-7ca218b6211d.jpg)

**Comment by mcf-nikai** [comment]
![default](https://cloud.githubusercontent.com/assets/24665918/22089595/8ff6e4ee-de2f-11e6-8887-e98ef411db47.jpg)

**Comment by mcf-nikai** [comment]
間違えてクローズしました。

**Comment by makitokezuka** [comment]
1/30 確認完了。Closeします。
