### ISSUE TITLE
問診終了画面で終了しようとすると「確認コードが違います」エラーになり終了できない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#101]
問診終了画面で終了しようとすると「確認コードが違います」エラーになり終了できない。
病院側で何か入力して終了できる仕様？

**Comment by makitokezuka** [comment]
ごめんなさい、確認コードはログインIDを確認コードに入力して正誤チェックしています。これは、患者側で勝手に画面終了して次の問診を入れないための仕様です。現在テスト環境としての確認コードは「1111」です。

**Comment by mcf-nikai** [comment]
ありがとうございます。
ソースコードから推測して（# 既に患者IDがあって、患者IDを変更する場合とコメントがあったので）修正するところでした。。。
