### ISSUE TITLE
基本情報登録画面（basic_information)で電話番号入力の際に、できればipad標準とは違う数値のみの入力パットを出したい。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#103]
過去のような感じをポップアップ出だすイメージです。
[https://gyazo.com/3235b9b88aef0182e59cad7121f9c70f](url)

**Comment by mcf-nikai** [comment]
名前はカタカナ、電話番号は数字のソフトウェアキーボードが出るようにしたい

**Comment by mcf-nikai** [comment]
こんな感じで実装出来そうですが、、、
本当にリリ－スする時は次の実装も必須になりますね。。

・多言語による切り替え
　→少しやりかけているようですが。。
★多言語切り替えで言語ファィルだけではなく、プログラム（上記のキーボード部分のJS）も、プログラム上で言語を意識して無効（標準キーボード）にしなければならない

**Comment by makitokezuka** [comment]
確認しました。下記実装可能ですか？
・名前の部分、名字と名前の間にスペースを入れたくなるので、スペースキーが欲しい。

おそらくデフォルトのモジュール使っていると思うので、難しいようであれば、氏名、ではなく、
入力欄を名字と名前で２つに分けたほうが良いですかね？

なお、上記以外のタッチ感としては問題ありません。

**Comment by mcf-nikai** [comment]
確認ありがとうございます。それではこのまま次回のpull requestに含めます。
スペースについては元々の機能としてありましたので実装しました。

**Comment by makitokezuka** [comment]
確認しました。OKです。
