### ISSUE TITLE
症状の発生時期・期間の次へいくとエラーになる場合がある

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#104]
![default](https://cloud.githubusercontent.com/assets/24665918/22098933/6c0c3858-de6c-11e6-9997-36e124b18842.png)

症状選択画面で何かしらの症状と、「他の症状はない」の両方を選択した時に誤動作を起こして発生していると思われる。

**Comment by mcf-nikai** [comment]
以下の様に修正します。

・「他に症状がある方は下記より選んでください」→「そのほかにも症状がある方は下記より選んでください」
・「他の症状はない」→「特に症状はない」に用語変更

かぜ用症状選択画面
　・「特に症状はない」チェックボックスを非表示にする
　・最低1つ選択するように必須チェックする
内科一般用選択画面
　・「特に症状はない」チェックボックスを選択すると、全てのチェックボックスをクリアする

**Comment by makitokezuka** [comment]
確認完了。Closeします。
