### ISSUE TITLE
随伴症状選択画面で「他の症状欄」（全身等）で症状の行をクリックしてもチェックされない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#106]
随伴症状選択画面で「他の症状欄」（全身等）で症状の行をクリックしてもチェックされない。
主訴と関連性の高い症状欄では行をクリックするとチェックされる。

**Comment by mcf-nikai** [comment]
主訴選択画面で「かぜ・胃腸炎」以外を選択すると発生する様子

**Comment by makitokezuka** [comment]
確認しました。close
