### ISSUE TITLE
症状の発生時期・期間で「現在はない」の値が」保持されていない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#108]
症状の発生時期・期間で「現在はない」の値が」保持されていない。
確認画面に行くと「現在はない」が表示されない。
値が保持されていないか、確認画面に描画する欄が無いか。

![default](https://cloud.githubusercontent.com/assets/24665918/22140821/1c00fc7e-df32-11e6-9ce0-864a41377365.png)

![default](https://cloud.githubusercontent.com/assets/24665918/22140833/343ddf6e-df32-11e6-886e-2496e0dc9ceb.png)

**Comment by makitokezuka** [comment]
確認完了。close
