### ISSUE TITLE
随伴症状選択画面で関連性の高い症状が無い場合でも枠だけ表示される

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#111]
随伴症状選択画面で関連性の高い症状が無い場合でも枠だけ表示されるので分かりにくい。
そもそも、「関連性の高い症状が無い」状態がほとんど発生しないなら、わざわざ手を入れなくても良いと思う。

![default](https://cloud.githubusercontent.com/assets/24665918/22139686/f1417f74-df2a-11e6-95b6-136cdb92530d.png)

**Comment by makitokezuka** [comment]
確認しました。OKです。
