### ISSUE TITLE
初診カルテ無しの場合、問診終了画面で「ID修正」欄に番号をいれてもDBに格納されていない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#112]
初診カルテ無しの場合、問診終了画面で「ID修正」欄に番号をいれてもDBに格納されていない。
UPDATE文は「...SET register_id= 0...」となっている。

![default](https://cloud.githubusercontent.com/assets/24665918/22140770/d048c05a-df31-11e6-8535-2cbeaa14c701.png)

**Comment by makitokezuka** [comment]
確認しました。OKです。
