### ISSUE TITLE
病気マスタの詳細画面でメインメニューが表示されているが無い方が良い

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#113]
病気マスタの詳細画面でメニューが表示されているが無い方が良い。
システムでは一般的にサブウィンドウにはメインメニューは表示しないようにします。

例えばサブウィンドウでログアウトして、その後メイン画面で操作しようとして動きがおかしくなるなど
、どうでも良いことの辻褄合わせるのが大変になるためです。

![default](https://cloud.githubusercontent.com/assets/24665918/22140736/a707d794-df31-11e6-8bb7-706a75de37a3.png)

**Comment by mcf-nikai** [comment]
@makitokezuka 
これは改修しても良いですか？
それともあった方が良いと思います？

**Comment by makitokezuka** [comment]
改修お願いします

**Comment by mcf-nikai** [comment]
確認ありがとうございます。
問診一覧からの編集画面も合わせてメインメニューは無くします。
代わりに「閉じる」のリンクを付けときます。

![popupwindow](https://cloud.githubusercontent.com/assets/24665918/22533057/fa94de00-e92e-11e6-9ae6-ac95b907ea94.png)

**Comment by makitokezuka** [comment]
確認しました。OKです。
