### ISSUE TITLE
症状の発生時期・期間のプルダウンの選択すると、下層にあるプルダウンもすべて引きずられる

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#115]
症状の発生時期・期間のプルダウンの選択すると、下層にあるプルダウンもすべて引きずられる
現象が発生したりしなかったりする気がする。。。

![default](https://cloud.githubusercontent.com/assets/24665918/22141164/f71abd9e-df33-11e6-812e-bdaf76e36beb.png)

![jan-20-2017-5-08-pm](https://cloud.githubusercontent.com/assets/24665918/22141203/39acafe6-df34-11e6-81d7-4c42adf01610.gif)

**Comment by makitokezuka** [comment]
@mcf-nikai 基本的には、下のプルダウンが引きづられるの仕様としてはOKなのですが、発生したりしなかったりするのはおかしいですね。

**Comment by mcf-nikai** [comment]
返信ありがとうございます。
発生しない場合があるというのは要調査として置いておくとして、連動の部分につきまして、、、

現在の連動の動きでは、既に「入力済」のプルダウンも変更されてしまうので危険ではないかと危惧します。
エンドユーザは一般人になるので、たとえ見えている部分でも連動している事に気付かない可能性が高い。
上から順当に進んでいるときは問題無いと思いますが、
思い直して上に戻って変更した場合、ちょっと危ないのではないかと思いました。
（このような局面が発生する機会は少ないですが、発生した時のリスクが大きい）

連動の目的としては、「入力の手間の軽減」の為と推測していますが、
問診システムにおいては、誤入力はかなりクリティカルな問題になると思いますので。

以下のような対応が考えられます。
１．一番上のプルダウンにかなり目立つように警告文を表示する
２．一番上のプルダウンを変更した場合、警告文をアラート表示した上で（或はYesNoで）連動する
　→全部未入力なら表示しない
３．未入力のプルダウンだけ連動する
４．プルダウンが全部同じ場合だけ連動する

**Comment by mcf-nikai** [comment]
本件については様子見ということでクローズします
