### ISSUE TITLE
問診確認画面で「未回答」はハイライトする。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#118]
問診確認画面で、何が未回答になっているか、わかりやすくしたいとの要件あり。
JavaScriptでの実装となるはずだけど、やり方がよくわからんかった。

**Comment by mcf-nikai** [comment]
少し面倒ですがruby側での実装になるのでは？と思います。
classを付加してcssか、rubyのhighlight()を使うか。

**Comment by makitokezuka** [comment]
確認しました。
