### ISSUE TITLE
病気一覧画面で最初に表示したときリストが表示されるが、クリックしても詳細が見れない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#119]
病気一覧画面で最初に表示したときリストが表示されるが、クリックしても詳細が見れない。
一度、検索するとリストをクリックして詳細を見ることができるようになる。

問診一覧は初期表示は必要と思うが、病気一覧は、症状一覧と同じで初期表示は不要と思う。

**Comment by makitokezuka** [comment]
確認しました。
