### ISSUE TITLE
完了画面から回答内容を表示する機能にて、左右の余白が大きく文字が無駄に折り返されてしまうので、文字表示領域をもっと広く取る。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#121]
下記のように症状の発生時期が折り返されてしまい、縦に長くなってしまうので、左右余白及び縦余白も減らして、もっとコンパクトに表示できると良いです。
<img width="385" alt="2017-01-25 17 36 03" src="https://cloud.githubusercontent.com/assets/16998229/22283326/eec91d80-e324-11e6-9e94-cb9ae8aa2e5d.png">

**Comment by mcf-nikai** [comment]
修正しました。

![medical_interview_steps_completed](https://cloud.githubusercontent.com/assets/24665918/22323107/c6647d34-e3e3-11e6-8805-51d76d3bb4ef.png)

**Comment by makitokezuka** [comment]
確認しました。OKです。
