### ISSUE TITLE
問診の病歴・生活習慣画面でアルコールと喫煙の回答欄の動きがおかしい

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#122]
・アルコールを「飲む」場合、飲む頻度、量のデータが次の画面へ保持されていない

・確認画面から戻ったり、確認画面から[編集]ボタンで表示されたとき、アルコールを「飲む」場合、飲む頻度、量の入力画面が表示されていない。

・確認画面から戻ったり、確認画面から[編集]ボタンで表示されたとき、喫煙を「する」場合、喫煙年数等の入力画面が表示されていない。

**Comment by makitokezuka** [comment]
確認しました。
