### ISSUE TITLE
問診一覧からの詳細画面にて、鑑別リストが表示されなくなっている。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#126]
いくつかテストしてみたが、全て抽出されなくなっているので、おそらくModel側のメソッドへの変数引き渡しが上手く行っていない気がする。

**Comment by mcf-nikai** [comment]
直接的には@@diagnosis_listsをコントローラの最初で初期化していた為、次の画面遷移で無条件に初期化されていました。
保持場所をクラス変数からセッションに変えました。
そしてセッションの保存場所をcookieからDBに変更しました。
以上から、確認時はdb:migrate:resetしてください。
以下の思考でクラス変数からセッションに変えましたが、クラス変数である事に意味（他の場所で利用していたり）があれば、すみませんが教えてください。

●2kai思考
---
１．そもそもなんでクラス変数なんだろう？？他は結構セッションに保持してるのに。。。
２．セッションにしようー。
３．cookieのサイズオーバーでエラー！ゲ！
４．。。。もしかしてそれでクラス変数？

**Comment by makitokezuka** [comment]
確かに思考通り、最初セッションに入れようとしたら、エラーが出て解決できなかったのでクラス変数としました。そのコントローラー以外では使っているところはありません。

**Comment by makitokezuka** [comment]
確認しました。sessionの使い方等勉強になります
