### ISSUE TITLE
確認画面（confirmation）で修正をしたら、後ろのロジックに影響ない場合は、確認画面に再度戻ってくるようにしたい。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#127]
現状、確認画面にて修正を押すと、その画面に戻り、その後はWizardどおりに画面遷移（他の入力画面も一通り通る）が、本来的には、後ろの画面に影響がない場合には、再度確認画面に一発で戻ってきたい。

**Comment by mcf-nikai** [comment]
全体見直してみました。
[Book1.xlsx](https://github.com/makitokezuka/symptom-interview/files/743481/Book1.xlsx)


添付の通り、影響なしの1箇所修正と、
修正しない場合は「次へ」で確認画面へ飛ぶ。

上記のような修正になるかと思いますが、イメージ合ってます？？

**Comment by makitokezuka** [comment]
イメージあっています。なお、風邪用問診を通った場合も同様の処理になりますが、処理の流れとして異なるViewを通るので、その点だけ気をつけてください。

**Comment by mcf-nikai** [comment]
①変更が無い場合は確認画面に戻るようにしました。
②「症状の発生時期・期間」は急性か慢性かの基準が変わると、その後に影響するので、変更する前の値と変更後の値を見て判断するようにしました。
③「風邪用問診の追加質問」と「症状発症のパターン」は影響しないので確認画面に戻るようにしました。
　→但し、現在は確認画面に２つとも出てこないので、、、#130の修正が完了したら生きてくるはず。

**Comment by makitokezuka** [comment]
確認しました。OKです。
