### ISSUE TITLE
病気一覧から詳細を表示するとデバッグのようなダイアログが表示される

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#131]
病気一覧から詳細を表示するとデバッグのようなダイアログが表示される。
N+1問題の検出。こんなチェックしてくれるんですね。
コントローラ側でincludesを追加しました。

![default](https://cloud.githubusercontent.com/assets/24665918/22534677/0572440c-e939-11e6-85e0-aef4e53524ed.png)

**Comment by makitokezuka** [comment]
gem でbulletというものをdevelopment環境だけ導入しています。
http://www.techscore.com/blog/2012/12/25/rails%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E7%B4%B9%E4%BB%8B-n1%E5%95%8F%E9%A1%8C%E3%82%92%E6%A4%9C%E5%87%BA%E3%81%99%E3%82%8B%E3%80%8Cbullet%E3%80%8D/

Gemfile 87行目
```
  #N+1検出のためのbullet導入
  gem 'bullet', :group => :development

```

修正ありがとうございます。

**Comment by makitokezuka** [comment]
確認しました。
