### ISSUE TITLE
全体的に、チェックボックス系の項目を選択して進むと、確認画面等から再編集してクリアしても、クリアされない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#132]
チェックボックスをクリアすると、コントローラ側ではnilと判定されるので、セッション情報に格納されないため。
value.present?となっているので、あればセッションに保存する。なければ何もしない（クリアもしない）になっているため。
アルアルですね。

**Comment by makitokezuka** [comment]
確認しました。
