### ISSUE TITLE
処方を希望する薬、薬の注意点など、チェックボックス全般的に「特になし」を用意する必要があるか？

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#134]
処方を希望する薬、薬の注意点など、チェックボックス全般的に「特になし」を用意する必要があるか？
チェックボックスの項目は全て、「チェック無し」が「無い」のか「未回答」なのか分からないので、全てにおいて「特になし」を用意する必要がある？

個人的は必要な気がしますが。

**Comment by makitokezuka** [comment]
作った方が良いですね。そのうえで必要ないと医師から指摘された箇所だけはずしましょう。

**Comment by makitokezuka** [comment]
確認しました。OKです。
