### ISSUE TITLE
確認画面から主訴選択画面に戻った時どれを選択していたか分からない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#135]
確認画面から主訴選択画面に戻った時、

１．ラヂオボタンが選択されていない
２．枠が閉じているので、選択済の項目が属する枠は開いた状態で表示してほしい。

**Comment by mcf-nikai** [comment]
随伴症状も同様にチェックボックスが選択されていない

**Comment by makitokezuka** [comment]
確認しました。修正ありがとうございます。
