### ISSUE TITLE
主症状選択画面で主症状を選択しても、次の随伴症状画面で正しく表示されない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#136]
![feb-3-2017-8-50-am](https://cloud.githubusercontent.com/assets/24665918/22573868/86382a6a-e9ee-11e6-8046-25c7042c6a25.gif)

**Comment by makitokezuka** [comment]
あ、これは仕様としては、正しくてデータの問題です。（レイノー現象というのも、しびれ、の一種です）主症状が複数紐づくカテゴライズのデータを辞めますので、この問題は解消されます。

**Comment by mcf-nikai** [comment]
了解しました。
Issueはデータ修正＆確認がとれるまで残しておきます。

**Comment by mcf-nikai** [comment]
元データの修正が必要なので毛塚さんをassignさせて頂きます。

**Comment by mcf-nikai** [comment]
確認しました。
SQLレベルで「主症状が複数紐づくカテゴライズのデータ」がなくなったこと。
実際の画面で主訴「しびれ」が進めるようになったこと。
クローズします。
