### ISSUE TITLE
問診開始画面で存在しない診察券番号を入れてもそのまま進むことができる

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#137]
番号チェックして、存在しない診察券番号は進めないようにした方が良い。

**Comment by makitokezuka** [comment]
これについては、α版では電子カルテから患者データの取り込みをしない点、及び、初診であっても診察券番号だけを先に発行してしまうオペレーション（→初診＋IDあり、と同様）も想定されたため、チェックをしない仕様にしています。

**Comment by mcf-nikai** [comment]
すみません。お手数をお掛けしました。
どうにも、受付スタッフと患者の入力の分担を忘れてしまいがちです。。。

クローズします。
