### ISSUE TITLE
問診選択画面の用語が分からない（と思う）

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#138]
患者には問診選択画面の区別がイマイチつかないのでは。。

１．「初診・カルテ無し」→「初診・当院は初めての方」
２．「初診・カルテ有り」→「初診・当院の診察券を持っている方」
３．「再診・予約」→「再診」で良いと思います。初診だけど電話（とかインターネトで）予約したとかだと、「予約」を選びたくなりそう。

ご検討ください。
言葉は大事なので修正は保留しておきます。

**Comment by makitokezuka** [comment]
問診選択画面は、患者ではなく、受付スタッフが、入力する画面のため、上記にしていました。
ただ、たしかに、わざと難しくする必要がないので、下記でOKです。

１．「初診・カルテ無し」→「初診・当院が初めての方」
２．「初診・カルテ有り」→「初診・当院の診察券を持っている方」
３．「再診・予約」→「再診の方」

※ちなみに、なぜ予約を再診に含んでいたかというと、このクリニックでは再診以外では予約（日時予約）を取っていなかった為です。あと、　初診と再診の違いが患者にとってわからず（医療保険の区分けを理解する必要がある）医療機関側の判断になる（初診料をとるか、再診料で保険を請求するか）ため、将来的にもこの選択肢の場合は医療機関側の操作画面となると思います。

**Comment by mcf-nikai** [comment]
すみません誤解していました。
提案の用語は受付スタッフには冗長だと思うので、３だけの修正にして様子を見させてください。

**Comment by makitokezuka** [comment]
確認しました。
