### ISSUE TITLE
主訴選択画面で「禁煙治療」等の主症状が無いものを選んだ場合、コンパイルエラーで先に進めなくなる

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#141]

**Comment by makitokezuka** [comment]
これは、データ・セットできていない問題です。禁煙治療、等の主訴（カテゴライズデータ）を消去する等の対応を取ります。

**Comment by makitokezuka** [comment]
データの問題なので、対応者を毛塚に変更。

**Comment by mcf-nikai** [comment]
もう少し残っているようです。
以下の２つの症状が主訴に紐づいていないためエラーになります。

**Comment by mcf-nikai** [comment]
確認しました。
SQL上で主訴に結びついていない症状がないこと、上記２つが先に進める事を確認しました。
クローズします。
