### ISSUE TITLE
問診終了画面で「リロード」するとコンパイルエラーになる

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#144]
#96 の修正がイマイチだったと思われる。
元々はリロードするとInsertが再実行されていたのだが、
「戻る」ボタンの対応をしているうちに、リロードの対応も「した気」になっていた。

**Comment by makitokezuka** [comment]
問診完了画面で、リフレッシュすると下記エラー画面となります。
https://gyazo.com/72a5bbb03269405a6ee2c48a7132667a

↑この動作で認識あっていますかね？別の動作をイメージしていましたか？

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
