### ISSUE TITLE
問診内容画面において、鑑別リスト一覧で何もチェックせずに「確定診断」「保留」するとサーバエラー

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#146]
問診内容画面において、鑑別リスト一覧で何もチェックせずに「確定診断」「保留」するとサーバエラーになる。

**Comment by mcf-nikai** [comment]
修正しました。
さらに、全てのチェックを外して「確定診断」「保留」した場合は、
問診表のステータスを「未完」に戻すようにしました。

**Comment by makitokezuka** [comment]
確認しました。
