### ISSUE TITLE
問診内容画面の鑑別リスト一覧で症状が多い場合に確率（オッズ）が「何の」確率なのか分かりにくい

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#147]
①列の区切り線が無いので分かりにくい
②スクロールするとタイトルが隠れるので分かりにくい

![default](https://cloud.githubusercontent.com/assets/24665918/22717446/7e1306cc-edde-11e6-86f7-8b99cd89b11d.png)

点数にオンマウスした時にツールチップでタイトルを表示するようにしました。

**Comment by makitokezuka** [comment]
なるほど、こういうやり方もありなんですね。ありがとうございます。
