### ISSUE TITLE
内科一般→主訴画面で、デフォルトで「かぜ・胃腸炎」が選択された状態になっている。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#149]
<img width="1250" alt="2017-02-09 16 15 50" src="https://cloud.githubusercontent.com/assets/16998229/22772988/16890564-eee3-11e6-82f4-aa70101a632a.png">

問診を開始して、主訴画面で、上記のように最初から選択された状態になっているが、本来は、何も選択されていない状態からスタートする。

**Comment by mcf-nikai** [comment]
内科一般を選んだ時も、問診票選択で「風邪・胃腸炎」を選んだ時にcategory_idを決め打ちする処理を通っていました。
#135を修正したことで顕在化したようです。。これもすぐ分かるデグレでした。

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
