### ISSUE TITLE
発熱詳細質問画面で、温度の入力について範囲指定をしたほうが良い。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#154]
発熱の範囲としては、35.0℃→42.9℃の範囲内であるため、それ以外の値が選択できることを避けたほうが良い。
方法として、Validationをかけても良いが、現状の入力形式でなく、プルダウン方式で予め範囲を設定しておいても良い。

**Comment by mcf-nikai** [comment]
プルダウンにしました

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
