### ISSUE TITLE
問診確認の詳細画面（interview_sheets/detail)で、印刷フォーマットに変更して印刷出来るボタンが欲しい

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#155]
問診システムと電子カルテ連携はしばらくする予定がないため、運用としては、問診詳細画面にて印刷を行い、通常の紙の問診票と同様の取扱（カルテへの挟み込み？PDF化して電子カルテへ添付）の運用を行う。
そのため、詳細画面にて問診内容の印刷ができるボタン及び印刷画面が欲しい。
※鑑別リストは一旦冗長になるので、印刷フォーマットには含めない。
※詳細画面にボタンがついていて、印刷フォーマット用画面に遷移してもOK

**Comment by mcf-nikai** [comment]
●システム全体で共通
コントローラで「set_print_url(url)」（ApplicationHelperに定義）で印刷画面へのURLをセットすると、ヘッダ領域に印刷リンクを表示するようにしました。

●問診詳細特有
印刷用画面を用意しました。
患者情報、症状、病歴等の各ブロックをパーシャル化して、印刷用画面と詳細表示で共有するようにしました。
印刷用画面は可能な限り1枚に収まるように、各ブロックの配置を変え（症状と病歴を逆にしました）、application.cssの「@media print」部において、bootstrapに定義されているクラスの、印刷時には不要な余白等を上書きして消すようにしました。
footer.cssも同様。

●関係ないけど
popupウィンドウの判定方法（ApplicationHelperに定義）を変えました。
コントローラ側でウィンドウの状態を設定するようにしました。

**Comment by makitokezuka** [comment]
確認しました。パーフェクトです。ありがとうございます。
