### ISSUE TITLE
診察券番号は数字のみで良いのか？

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#157]
現在DBのデータ型がintegerになってますが、本当数字のみでOKでしょうか？
それであれば、入力チェックする必要があります。
現在は数字以外を入力すると、暗黙に診察券番号「0」で登録されています。

個人的にはDB上は文字列型で、入力チェックで「英数字」で良いと思いますが。

※数字限定なら、ここも数字キーボード出した方が良いですね。ipadでの操作なので。
※ログインIDもintegerになってますので上記と同様。

**Comment by makitokezuka** [comment]
数字以外も可能性としてはあり得るので、DBのデータ型を変更する必要ありますね。ごめんなさい。

＞個人的にはDB上は文字列型で、入力チェックで「英数字」で良いと思いますが。

まずは、この対応で良いと思います。

**Comment by makitokezuka** [comment]
処理内容確認しました。
