### ISSUE TITLE
問診詳細画面の症状欄の「主訴」と「有無」が何を表しているか分からない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#160]
●「主訴」
時間の都合上「1」「2」の表記になっているだけだと思いますので、「1」→「○」「2」→「空白」に表示を変更しようと思います。

●「有無」
これはプログラムを見ても意味が分かりませんでした。
過去の残骸でしょうか？#136 #141 に絡んでこれも廃止と思って良いのでしょうか？？

![default](https://cloud.githubusercontent.com/assets/24665918/23046182/770213aa-f4eb-11e6-8697-4e2df98bbf26.png)

**Comment by mcf-nikai** [comment]
主訴が複数あった場合の画面のデータで、主訴複数を無くすのであれば不要（とりあえず画面上には出さない）と判断してOKでしょうか？
画面が狭いので不要なものはなるだけ削ろうとしています。

![default](https://cloud.githubusercontent.com/assets/24665918/23111908/37a1d890-f76f-11e6-8fe1-713657978a6f.png)

**Comment by makitokezuka** [comment]
@2kai 
＞時間の都合上「1」「2」の表記になっているだけだと思いますので、「1」→「○」「2」→「空白」に表示を変更しようと思います。
→　お願いします。

有無については、上記ご推測のとおり、主訴に紐づく複数症状がある場合を想定していましたが、データ上無くなるので、こちら画面上表示無しでOKです。

**Comment by mcf-nikai** [comment]
実装済なのでcloseします
