### ISSUE TITLE
患者が既に登録されていた場合、基本情報画面でエラーになる。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#161]
既存の患者情報が登録されている再診や、初診カルテ無し（診察券番号=1111など）の場合、基本情報画面でエラーとなる。

 ` @birthday_date ` の形式違いによりエラーとなる。
<img width="1373" alt="2017-02-20 10 56 07" src="https://cloud.githubusercontent.com/assets/16998229/23109434/9bf51f72-f75c-11e6-92e5-3c7cc0a63dd0.png">

※どの修正での対応かは不明だが、

173行目
``` medical_interiview_steps_controller.rb

    if @birthday_date.present?
      d1 = Date.new(@birthday_date["date(1i)"].to_i,@birthday_date["date(2i)"].to_i,@birthday_date["date(3i)"].to_i).strftime("%Y%m%d").to_i
      d2 = Date.today.strftime("%Y%m%d").to_i
      session[:sheet]["age"] = (d2 - d1) / 10000
    end

```

上記部分で、上記は、session[:sheets][:birthday]に入力されている場合は、取り出せる形式（String？)だが、既に患者が登録されている場合は、 ` @birthday_date ` が Date classであるため上記だとメソッドエラーとなる。

**Comment by mcf-nikai** [comment]
#158の修正で、鑑別質問及び画面表示でそれぞれ生年月日をベースとして「年齢」を算出しているロジックがあったので、1箇所にまとめた（生年月日が確定した時に算出してセッションに保持）時のデグレでした。

**Comment by makitokezuka** [comment]
基本情報登録画面に遷移した際に、@birthday_dateがnilになっていて、どんな生年月日の人もデフォルトの1955年5月15日がセットされている。

**Comment by mcf-nikai** [comment]
patientデータが存在していた場合（診察券番号を指定した場合）、
セッションに保存せずクラス変数のみ利用していたため、
セッションベースでデータを展開する部分load_dataでnil（保存していないので）に初期化されていた

**Comment by makitokezuka** [comment]
確認しました。
