### ISSUE TITLE
その他の症状、等SQLエラーを起こすカテゴライズが存在する。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#165]
その他の症状、をカテゴライズで選んで進んでいくとSQLエラーが起きる。
<img width="1295" alt="2017-02-24 12 02 52" src="https://cloud.githubusercontent.com/assets/16998229/23288861/4d30c942-fa89-11e6-95fe-957a75876592.png">

※おそらく症状のセットなどデータに不備がある模様。

**Comment by mcf-nikai** [comment]
データの問題というより、プログラムで対応した方が良いように感じます。
「症状の発生時期」画面で決定した時期（慢性or急性）により、リストアップした病気マスタを絞込んだ結果、該当する病気が存在せずにSQLエラーが発生しています。

「慢性or急性」で絞り込んだ結果、病気が存在しない場合は、
絞り込まずに病気をリストアップしてはどうでしょう？？

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
