### ISSUE TITLE
ipadのデスクトップにショートカットを作成した場合にアイコンを表示したい

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#168]
ipadのデスクトップにショートカットを作成した場合に、ロゴをアイコンとして表示したい。
現在は画面コピーのようなアイコンになる。

**Comment by makitokezuka** [comment]
こちらは確認しましたが上手くいきません。
![img_5921](https://cloud.githubusercontent.com/assets/16998229/23396307/9b76a874-fdd6-11e6-94d2-42713c3d35a2.JPG)

![img_5922](https://cloud.githubusercontent.com/assets/16998229/23396306/98543ac6-fdd6-11e6-9b6d-a403f32b1fb8.JPG)

![img_5924](https://cloud.githubusercontent.com/assets/16998229/23396319/aa0d4f50-fdd6-11e6-9a62-a0e83b683d97.JPG)

**Comment by mcf-nikai** [comment]
確認ありがとうございます。こちらでも確認できました。
修正してpushしたので、お手数ですが、もう一度ご確認お願いします。

**Comment by makitokezuka** [comment]
確認できました。ありがとうございます。
