### ISSUE TITLE
患者の問診完了後、スタッフ側で補足情報等を入力できる項目が欲しい。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#176]
患者が問診完了後、医療機関側画面にて、スタッフあるいは医師にて補足情報を入力できる項目が欲しい。画面としては、問診詳細画面。

**Comment by mcf-nikai** [comment]
編集機能を付ける時に一緒に実装しましょう。
長くなりがちですが「症状」エリアですね。

**Comment by makitokezuka** [comment]
エリアは、別個に一つ作った方がよいイメージです。「コメントエリア」として。

**Comment by makitokezuka** [comment]
確認しました。OKです。たぶん、将来的に、「誰が入力したのか？」「いつ入力されたのか？」も記載できるようにしたい、という要望が上がるような気がします
が、一旦これで運用見てみます。

**Comment by mcf-nikai** [comment]
将来的に、「誰が入力したのか？」を実装する場合、わざわざ「自分の名前を入れる」システムは見たことありませんので、ログインの機構（今は病院がログインIDを持っているので、これをユーザ管理する必要があります）から、変えねばなりませんので、ちょっと大変スね。

YAGNIですが、その時が来たらやります。
