### ISSUE TITLE
基本情報登録画面にて生年月日がデフォルトセットされているため、変更しない場合がある。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#177]
生年月日のデフォルト値セットを辞める。

**Comment by makitokezuka** [comment]
生年月日だけでなく、他のプルダウンにも言えることだが、現在のデザインテンプレートだと下にしか出てこないため、自分の年齢を選ぶのが手間。
本来やりたかったこととしては、真ん中ぐらいからスタートして、上か下かにロールしていくようなプルダウンにしたかった。

**Comment by mcf-nikai** [comment]
ドラムロール（通常の）のプルダウンが無いか探す

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
