### ISSUE TITLE
アレルギーの記入でありの場合、何のアレルギーか入力できるようにしたい（新規項目追加）

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#178]
病歴画面にて、アレルギー有無の項目があるがありの場合、何のアレルギーか選択？あるいは自由記入の欄が欲しい。
※ただし自由記入にすると、いままで頑なにipadのキーパット入力の項目をなくしてきたのに反するので方法は悩ましい。チェックボックス形式が良いかも。

**Comment by makitokezuka** [comment]
アレルギーの質問項目としては下記を想定。

（１）アレルギーはあるか？　→　Y/N
何のアレルギーがあるか　→　薬／食べ物／その他　（複数選択可）
具体的にアレルギーのあるものを選択ください
　→　薬：
　・抗生物質（ペニシリン）、解熱鎮痛剤、ビタミン剤、漢方薬、ホルモン剤、下痢止め、造影剤、ステロイド塗り薬、その他
　　食べ物：
　・卵、牛乳、小麦、カニ・エビ、蕎麦、果物、ピーナッツ、魚、その他

**Comment by makitokezuka** [comment]
確認しました。
問診表上の表記が、「ある」を選んだ場合、「アレルギー物質」となっているが、
これを「何のアレルギーがありますか？」に変更したほうが良い。
ただし、その場合、サイズによっては折り返しになってしまうので、ボタンのサイズ、配置調整が必要。

※すいません、私の方で調整しようと思ったのですが、CSSがどこに表記されているのか、追いきれず。。。

**Comment by makitokezuka** [comment]
すいません、もう一つ！お願いします。
問診確認画面、及び医療機関側の問診詳細確認画面にて、アレルギー物質の表記を、
食物：カニ・エビ,果物,その他
薬：解熱剤,
等とすることは可能ですか？

**Comment by mcf-nikai** [comment]
修正しました。

現在アレルギー項目に関しては「特になし」を選択項目として用意していません。
よって「未回答」なのか「特になし」かわかりませんので、
未選択の場合はそのまま空白を表示し、ハイライト表示や「特になし」の表示はしていません。

**Comment by makitokezuka** [comment]
確認できました。ありがとうございます
