### ISSUE TITLE
初診の場合は、住所入力を必須として欲しい。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#179]
初診の場合、住所入力を必須（電話番号等同じ）にしないと業務上ダメっぽい。

**Comment by mcf-nikai** [comment]
「カルテ無し」の場合必須チェックするようにしました。

しかしI/Fがテキスト入力のみは微妙な気がします。
郵便番号からの入力支援が欲しい気がする。
欲を言えば、「＊＊＊丁目」のように丁目違いでリストアップされて、その中から選択するヤツだ良いだろう。。。
