### ISSUE TITLE
問診結果の表示画面（医療機関側確認画面）で、電子カルテへの入力フォーマットに合わせたい

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#181]
電子カルテのS欄に入力するフォーマットに変更したい。どんな形式なのかは、後日サンプルをもらう約束。

**Comment by mcf-nikai** [comment]
やはり、CSV等の取り込み機能は無いのでしょうか？？

**Comment by makitokezuka** [comment]
まだ電子カルテ側と話はしていないですが、現在のオペレーションで言うと、
（１）患者が問診を記載
（２）記載された問診票を見ながら電子カルテのS欄（主訴欄）に受付が問診記載内容を解釈しながら記入。（→医師が見やすいフォーマットに変換している）

まずは、上記（２）のためのそのまま入力できるフォーマットに変換してあげた上で、その次として、電子カルテ側と調整の上、CSV取り込み的なI/Fの連携に入りたいと思います。
なお、入力フォーマットはこのような形です。
[問診入力フォーマット一覧（電子カルテ用）.pdf](https://github.com/makitokezuka/symptom-interview/files/829389/default.pdf)

**Comment by mcf-nikai** [comment]
問診の詳細画面の左「患者基礎情報」の下に「電子カルテ用フォーマット」として配置しました。

先頭行：問診のテンプレート名を表示
隔離表：タイトルのみ表示
主訴：主訴＋「関連性の高い症状」をリストアップし、+/-でマーキング。
　　　その他の症状から選んでいた場合は、末尾に追加
現病歴：主訴（風邪の場合現状データが無いので正確には1行目）の症状の期間から
　　　　日付を算出して表示
　　　　本日から　→　診察日から
　　　　昨日から　→　診察日-1日から
　　　　2〜3日前から　→　診察日-3日から
　　　　1週間ほど前から　→　診察日-7日から
　　　　2週間ほど前から　→　診察日-14日から
　　　　2週間以上〜1ヶ月以内　→　診察日-1ヶ月～診察日-14日から
　　　　1ヶ月以上前　→　診察日-1ヶ月より前から
既往歴：病歴をリストアップし+/-でマーキング
　　　　→リストはDB化していないが、プログラム上でコード管理するようにした。
　　　　　データもコンバート。
　　　　　本画面ではコードから「別名」（HTN等）に変換して表示するようにしている
アレルギー：食物と薬に分けて表示。
　　　　→無い場合は（-）
　　　　→ある場合は選択した項目を羅列する
嗜好品：喫煙と飲酒に分けて表示
　　　　→無い場合は（-）
　　　　→ある場合は各項目をサマリにまとめて表示
身体所見：体温を表示（風邪じゃなくても常に出力する）

**Comment by makitokezuka** [comment]
確認しました。一旦こちらで実装してみて、使えるかどうかを先方に確認してみます。再度修正が入ると思いますが、その際には別途issue立てます。
