### ISSUE TITLE
ipadのオリジナルのソフトウェアキーボードの反応速度が遅い

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#182]
ipadの入力支援の反応速度が遅い

**Comment by mcf-nikai** [comment]
●実装の考察（メモ）
タッチスタートイベント（ipad用）と、マウスダウンイベント（PC用）の両方を仕掛ける。
但し、ipadでは両方のイベントが発生する（しかしマウスダウンイベントはダブルタッチを判定する為に遅めに発生する）ので、本イベントが共通のアクションで発生した事を両イベント関数で共有する方法を考える。

**Comment by makitokezuka** [comment]
確認しました。
