### ISSUE TITLE
問診選択画面で診察券番号を入力した場合、複数のデータが該当した場合は選択できる画面が必要

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#186]
システム上、問診終了時に入力された診察券番号が「正しいか」を判断することができないため、誤入力を検知できない。
これをそのまま放置すると、次回（再診時）に予期しない動作をする事が想定されるので対応要。

問診終了時に、診察券番号が存在した場合に警告を出す（同一人物かの確認）か、
問診開始時に存在する人をリストアップする等対応を検討する必要がある。

以下は実際の運用DBだが、再診時に問題を引き起こす可能性が高い
![default](https://cloud.githubusercontent.com/assets/24665918/23593129/390121e8-024e-11e7-8038-40713faae02c.png)

**Comment by mcf-nikai** [comment]
重複を無くす方向で修正する。
既に存在した場合は確認メッセージを表示して（２段階）で更新する。

**Comment by mcf-nikai** [comment]
問診のデータ（interview_sheet）は、patient.id（register_idではない）と結びついているので、
patient上で重複を無くせない（リンク構造から変えるという手もあるが影響範囲が大きくなる）ので、
診察券番号が既に存在した場合、「入力した診察券番号は、既に＊＊さんとして存在します。このまま同一人物としてデータを登録しますか？」とメッセージを表示するようにしました。

「No」選択の場合は、問診終了画面（診察券番号入力画面）のまま、
「Yes」の場合は、今まで通り、リンクしているpatientレコードに診察券番号を設定するようにしました。
問診選択画面で「診察券番号」を入力した場合、
patient情報は作成日が一番新しい情報を参照するようにしました。

patientを1レコードには出来ていませんが、
逆に（当時の記録として）正確な情報が残せ、
システム利用時は最新の情報が引っ張られるので問題ないかと思います。

**Comment by makitokezuka** [comment]
確認できました。ありがとうございます。
