### ISSUE TITLE
問診一覧画面で、行をクリックしたら、詳細が表示されるようにしたい。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#187]
<img width="1375" alt="2017-03-08 15 44 01" src="https://cloud.githubusercontent.com/assets/16998229/23693145/51c6c84e-0416-11e7-9d32-a3cd4882a75e.png">

**Comment by mcf-nikai** [comment]
操作性は統一した方が良い（前職では良くクレームに繋がっていました。「こっちの画面はこうなのに、、、」）ので、「病気一覧」「症状検索」「問診一覧」も同様ですね。

●実装の考察
trにjavascriptのイベントを仕掛けると、右端のボタンクリックした時にバッティングを起こして、ウィンドウが二重に開く事になると思うので、ボタン列以外の全列（td）にonclickイベントを仕掛ける必要がある。
このように大量にイベントを登録する場合は、正にJQueryが適している。

●余談
JQueryの名前の由来はJSelectらしい（http://www.koikikukan.com/archives/2012/07/04-015555.php）ので、まさにこのような局面で利用するライブラリなのでしょう。

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
