### ISSUE TITLE
運用環境で動作不良が起こっても特定できない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#188]
以下のようにherokuのログはステータスコード（HTTP500）しか情報が無い。

![default](https://cloud.githubusercontent.com/assets/24665918/23693222/ba63b43e-0416-11e7-810b-afb116ee4ea8.png)

**Comment by mcf-nikai** [comment]
以下を参考にgemを修正しました。

http://qiita.com/pugiemonn/items/0e69b7a29a384b356e65

**Comment by makitokezuka** [comment]
こちらも確認済み。Closeします。
