### ISSUE TITLE
問診結果の詳細画面で風邪用の追加質問画面が表示されない。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#191]
一般内科の問診から、主訴としてかぜ・胃腸炎を選んで進んだ場合、問診としてはかぜ用追加質問画面を通っているが、詳細画面上表示されない。

＜原因＞
_symptoms_pattern.html.erb 72行目
```
 <% if @interview_sheet.template_id == 2 %>
  <div class="panel-heading">
      <h5 class="panel-title">風邪用追加質問</h5>
```

この場合、一般内科の問診から来ているから、template_id=1のため、表示されない。
しかし、その後、主訴でかぜ胃腸炎を選んでいるので、風邪用問診を通っている。
判断ロジックを、template_id ではなく、categorise_id == 1001（かぜ胃腸炎）とすれば良い。

**Comment by mcf-nikai** [comment]
medical_interview_steps_controller.rb側は、「is_category_cold?」関数で判断するようにしましたが、画面側が漏れていました。
本関数をapplication_helperに持ってきて、共有するようにします。

**Comment by makitokezuka** [comment]
確認できました。ありがとうございます。
