### ISSUE TITLE
問診のどこかにフリーの入力欄を作りたい。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#192]
要検討だが、患者が自由に記載できる入力欄があっても良いと思われる。

現在、現場では、何か他に伝えたい事があれば、別途紙を渡して運用しているとのこと。

**Comment by mcf-nikai** [comment]
病歴・生活習慣画面の「診察に関する要望」のエリアに、「その他ご要望・ご質問・伝達事項等あればご入力ください」としてテキストエリアを追加してはどうでしょか？

他に検討する事があればご指摘の程お願いします。

**Comment by makitokezuka** [comment]
上記で問題ありません。

**Comment by makitokezuka** [comment]
確認できました。ありがとうございます。
