### ISSUE TITLE
問診の症状の期間入力において、選択肢に「本日から」を追加したい

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#193]
Pastsに「本日から」のデータを追加。
ただし、発症期間は、慢性か急性か？の判定で使っているので、その点を注意。
判定場所は、
medical_interview_controller.erb 363行目
```
#症状パターン
  def step_symptoms_pattern
    
    #次の画面に行けるか？の処理
    if params[:to_fever_detail].present?
      past = Past.find_by(id: @symptoms_period)
      @onset = Onset.find_by(id: past.onset_id).onset_name
      if @onset == "慢性"
        if session[:sheet]["onset_pattern"].nil?
          if !(param_validate(params_key: :onset_pattern, message: "症状の経過を一つ選んでください"))
            params.delete(:to_discrimination_question)
            params[:to_symptoms_pattern] = "to_symptoms_pattern"
          end
        end
      end
    end
`````

**Comment by mcf-nikai** [comment]
これは病院側の要望として「本日から」を病気の判定として切り分けたいのか、
患者さんが「今日からなんですけど・・・」的に、単に「選択肢が無い」という問題なのか？

後者であれば、「昨日から」の用語を「今日または昨日から」にするのはどうでしょう？
修正が楽ですし、患者さんも選択肢（プルダウンの数）は少ない方が良いと思います。

**Comment by makitokezuka** [comment]
要望としてあがったのは、『患者さんが「今日からなんですけど・・・」的に、単に「選択肢が無い」』の方ですね。ただし、今後切り分けたい、という要望は必ず出てくると予想される（急性の中でも1日たっているのか、数時間以内なのかは鑑別上考慮するため）ので、選択肢を増やす方向で対応しておいたほうが結果としては良いかと思います。

**Comment by mcf-nikai** [comment]
なるほど、了解です。

**Comment by mcf-nikai** [comment]
idを変更（現在は「昨日から」が「id＝1」なので）すると、既存データのコンバートが発生するため、
「本日から」のidは「7」として、別にdispカラムを追加しました。
選択肢を取得することろでは、dispカラムでソートして取得するようにしています。

DB構造変更＆pastテーブルのデータ投入が必要なため、デプロイに注意すること。

**Comment by makitokezuka** [comment]
確認できました。ありがとうございます。
