### ISSUE TITLE
病気一覧において、編集アイコンから詳細を表示するとエラーになる病気がある

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#195]
「痛風・高尿酸血症」「2型糖尿病」など

https://gyazo.com/73a2fdd5a90c98c019e1e55290239903

**Comment by mcf-nikai** [comment]
categorise_disease_relationsテーブルに、存在しないcategory_idが指定されたレコードが131件あるようです。

![default](https://cloud.githubusercontent.com/assets/24665918/23742624/f05ab1e8-04f0-11e7-98b8-9e3c76c673d8.png)

**Comment by makitokezuka** [comment]
ごめんなさい、これ問診側から見て必要ないcategoriseを消したせいで、完全にデグレっちゃいました。早急に対応策考えます。

**Comment by mcf-nikai** [comment]
病気一覧からの詳細画面表示で「痛風・高尿酸血症」「2型糖尿病」がエラーにならない事、
存在しない「categorise_id」及び「disease_id」を指示したデータが無い事を確認しました。
