### ISSUE TITLE
「症状の発生時期・期間」で主訴の「症状の発症時期」を選択せずに、随伴症状の時期だけを選択して次の画面に行こうとするとエラーになる

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#196]
「症状の発生時期・期間」で主訴の「症状の発症時期」を選択せずに、随伴症状の時期だけを選択して次の画面に行こうとするとエラーになる。

大久保総合内科で起きている現象です。

**Comment by makitokezuka** [comment]
確認しました。発見＆対応ありがとうございます。
