### ISSUE TITLE
喫煙習慣が回答済にも関わらず、詳細画面で見たときに未回答になる

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#199]
喫煙習慣が回答済にも関わらず、詳細画面で見たときに未回答になる。
セッションに保存した時（問診中）は「1」「2」等の数値、DBから取得した時は「past」「currently」等の文字列として、データが表示用の整形処理に渡されるので、DBから取得した時の整形処理がうまくいっていない。

**Comment by makitokezuka** [comment]
確認出来ました。ありがとうございます。
