### ISSUE TITLE
問診詳細画面で表示される「喫煙量」が正しい値で表示されない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#201]
ウィザード中でセッションに保存されているのは画面上の日本語「２箱以上」等が保持されている。
しかしDB上では数値が保存されている。
詳細画面で表示する時は、DB値をそのまま表示しているので、実際には違う「喫煙量」が表示されている。

※以下のような値がDBに保存されている。
たまにもらう程度→1
10本以下→10
２箱以上→２

**Comment by mcf-nikai** [comment]
DBのカラムがintegerになってました。
最初（CreateのSQL）からintegerなので、modelにenumの定義漏れじゃないかと思いますが、#199のように表示上の修正等がややこしくなるので、今回はカラムをstringにしました。

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
