### ISSUE TITLE
問診一覧画面で、新しい問診レコードが出来た際に、画面をリフレッシュしたい

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#221]
現在、問診一覧画面は、リフレッシュしない限り更新されないが、下記条件下でリフレッシュされるようにしたい。

（１）新しい問診が出来たタイミング
（２）詳細画面に入って、何か更新して（例えば確定診断とか）一覧に戻ってきたタイミング

**Comment by mcf-nikai** [comment]
実装が難しいです（正確には難しいというより、良く考える必要があります）ね。

WEBの特性上、サーバからクライアントへ指示を出すことは出来ませんので、クライアントから更新が無いか？を定期的にチェックしに行く必要があります（コソっとチェックすることであたかもサーバからの指示で動いているように見える）。
上記の通りなので、どうしても時差が発生し、時差を短くすればするほど、サーバの負荷が高くなります。

この「画面更新チェックの処理」（リクエスト）は全画面で発生し、かつ利用していないブラウザ（ブラウザ立ち上げているだけで、使っていない状態）も含めて全てで発生するので、、、1リクエストを如何に軽く処理するか？を突き詰めて実装しないといけません。
今は「大久保総合内科」だけなので、あまり問題にはならないと思いますが、
「たくさんの医院」が使いだしたときに、倍々ゲーム的に膨大なリクエストが発生し、
下手な実装をすると相当なサーバスペックを要求する可能性を秘めています。

**Comment by makitokezuka** [comment]
確認しました。ちなみに、どういう実装方法となったのか教えてもらえますか。

**Comment by mcf-nikai** [comment]
以下2つを実装しました。
・詳細画面で推論保存、診断除外したときは、メイン画面（js的には親画面）を更新するようにした。

・問診一覧画面は20秒毎に更新チェックして、更新されていれば『検索』を実行。

Websocketでの実装については、問診システムではオーバースペックと判断し見送りました。
ユーザーが増えた時に20秒間隔で耐えられないとしたら、それは実装よりスペックの問題と言えます。問診システムでWebsocketを検討するのは、同期間隔において完全なリアルタイム性を検討する必要が出たときだと思います。

**Comment by makitokezuka** [comment]
了解しました。ありがとうございます。
