### ISSUE TITLE
問診で風邪・胃腸炎を選んだ場合、「症状」として「風邪・胃腸炎」のデータが作られない

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#231]
問診で風邪・胃腸炎を選んだ場合、「症状」（主訴）として「風邪・胃腸炎」のデータが作られない。

問診で進んでいく場合、「風邪・胃腸炎」の場合は症状選択が必須になるため、動きとしてはある意味正しいとも言える（症状として「風邪・胃腸炎」はなんだかおかしいですし）が、そうすると、全体として（現在は主訴）の「症状の発症時期」を保存する場所がなるなる。

上記から、主訴として「風邪・胃腸炎」は登録した方が良い。

**Comment by makitokezuka** [comment]
こちら、そうですね。かぜ胃腸炎は色々悩んでマスタデータとしても、symptom_id=1179 "かぜ・胃腸炎"として一つの症状として立てたんでした。
主訴として「かぜ・胃腸炎」を登録するためでしたので、主訴として、「かぜ・胃腸炎」登録でOKです。

**Comment by makitokezuka** [comment]
ただし、表示として「かぜ・胃腸炎」＝厳密には「症状」ではないため、主訴としてこの表示がでるのも違和感があるのは事実。
表示側だけ対応すると、こんどは「かぜ胃腸炎」の実装だけどんどん特殊になって嫌だなぁと考えたのが大本の原因です。
対応策として、
（１）主訴は、symptom_id=1179 かぜ・胃腸炎　で登録する。（cateogorse_id =1001 (かぜ・胃腸炎）の主訴(categorise_symptom_relation table のrelation_flag=1））
（２）表示側としては、主訴＝かぜ・胃腸炎、として表示される（症状期間や、医師確認画面でも）が、そこはそのままにしておき、表示としておかしいと指摘された場合に少し実装方法を考える。

**Comment by mcf-nikai** [comment]
異論はありませんのでそのように修正しました。

**Comment by makitokezuka** [comment]
これについて、実装方法と私の認識で齟齬がある気がします。
「かぜ・胃腸炎を、主訴として登録する」→
カテゴライズとして、1001＝かぜ・胃腸炎、を選んだ場合、
symptom_id=1179（かぜ・胃腸炎）の症状を、answered_symptoms tableに登録する、という実装に変更する、と認識していました。
いま、どうなっているのか、別途相談させてください。

**Comment by mcf-nikai** [comment]
「answered_symptoms tableに登録する」という実装で私も認識してます。

最初のテンプレート選択で、一般問診で風邪を選択した場合はOKでしたが、
風邪用問診を選択した場合、修正した箇所を通らず、answered_symptoms tableにレコードが出来ていませんでした。
要はバグってました。すみません。。。

また、「風邪・胃腸炎」の場合ガチで「symptom_id=1179」を判断していましたが（コードに1179を記載していましたが）、他と同じように「categorise_symptom_relation」を参照して、たまたま「1179」になる。というように修正しました。

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
