### ISSUE TITLE
問診終了画面で、ipad標準キーパッドの「Go」ボタンで終了出来ていたが、終了出来なくなった

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#232]
問診終了画面で、医療機関側の操作として、確認コードを入れるために、ipad標準のキーパットが出てきて、確認コード入力後、[Go]ボタンを押すと、「問診終了」ボタンを押したことと同じ操作となっていたが、いつの時点からか、Goを押しても終了出来なくなった。

これは、操作上確かめたが、何回も繰り返す操作のため、「Go」ボタンで、問診終了できるようにししたい。

**Comment by mcf-nikai** [comment]
#186の修正でデータ更新の前に番号チェックをajaxで行うため、
問診終了ボタンの種類をsubmitからbuttonに変えてonclickアクションを実装したためでした。
submitに戻して、formのsubmitアクションをフックする（問診終了ボタンonclickアクションではなく）ようにしました。
