### ISSUE TITLE
問診の下部ボタン　戻る・次へ　が隠れることがある

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#234]
#233 がこちらの原因とも関連しているかはわかりませんが、こちらは特定画面で発生。

病歴画面で、「診察に関する要望」のエリアが、「戻る・次へ」のレイヤーより上に設定されているため、ボタンが隠れてしまう。
<img width="812" alt="2017-03-23 12 10 01" src="https://cloud.githubusercontent.com/assets/16998229/24230555/0ad14fb4-0fc3-11e7-8a86-f5d63ccc3967.png">

**Comment by mcf-nikai** [comment]
こちらは潜在的にずっとあったようです。
z-indexは不要なのでcss削除しました。

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
