### ISSUE TITLE
医師の診断結果を入力する部分の文字をもろもろ変更したほうが良い。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#236]
問診確認詳細画面にて、医師の診断結果を入力するにあたって、その診察で確定、とするには少し抵抗があるので、いろいろ表記を変えたほうが良いとのこと。

（１）左側のチェックのタイトル：　診断　→　推論
（２）右上の「確定診断ボタン」：確定診断　→　推論保存
（３）保留ボタン：保留　→　診断除外(ボタンの色をグレー等に変えたい）

また、下記要望もあり、実装可能な範囲で実装希望
（A）行をクリックしたら、チェックされるようにしたい。（推論チェックがつく・外れる）
（B）推論チェックされた行の色を変えたい
（C）推論チェックした後、推論保存を押さずに画面を閉じてしまうことがあるので、推論チェックがなにか変更されたら、ポップアップでの注意メッセージ＋保存するボタン、を出して欲しい。

**Comment by mcf-nikai** [comment]
（１）、（２）、（３）の用語、（A）、（B）は、そのように実装しました。

（３）の色については、推論チェック」を変更した時に、
確定診断のボタンの色を変えるようにしました。
デフォルトは推論保存も診断除外も「色なし」としています。

（C）については、「ページがアンロードされるときに発生するイベント」にて警告を出すようにしましたが、以下のURLに記載の通り、カスタムメッセージを表示できなくなっていました。
よってデフォルトの良く分からないメッセージが表示されてしまいます。
また、「チェックを付けて、外した」ものも変更対象としています（そこまで細かなチェックはしていない）

http://qiita.com/nantekkotai/items/9a6e2c98ed704934ab47

とりあえず、最低限の目的だけは達成できるかと思います。

**Comment by makitokezuka** [comment]
確認できました。ありがとうございます。
