### ISSUE TITLE
問診詳細確認画面（及び印刷画面）での生年月日表記を、和暦も表記して欲しい

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#237]
電子カルテは和暦で記入することが多いから、とのことです。

**Comment by mcf-nikai** [comment]
「和暦も」とあるので、「年」に関しては、西暦と和暦の両方を表示するようにしました。
この関係で横が長くなりますので、以下のように配置を変えました。

●もともと
年齢　３７（1979/12/3）
性別　男性

●修正後
年齢（性別）３７歳（男性）
生年月日　　昭和５４（１９７９）年１２月３日

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
