### ISSUE TITLE
発熱詳細質問画面での発熱のプルダウンをプルダウンではなく、数値入力にしたい

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#241]
プルダウンだと使いづらいとの指摘あり。
下記に変更。

・数値入力エリア＋電話番号と同様に入力支援キーパット
・入力された数値が、35度以下、あるいは43度以上の場合、「体温の入力が正しくありません。35度〜43度の範囲で入力ください。」としてvalidationメッセージを表示する。

**Comment by mcf-nikai** [comment]
テキスト入力及び温度範囲の入力チェックを実装しました。

**Comment by makitokezuka** [comment]
確認出来ました。ありがとうございます。 #243 のduplicateがあるが、こちらはclose
