### ISSUE TITLE
病気の鑑別リストにてOnsetの考慮が少しおかしい気がする。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#245]
Disp_disease.rbにおける、disease_target_listメソッド内にて、Onsetの考慮が少しおかしい気がする。
要調査。

**Comment by makitokezuka** [comment]
どうも、Onsetで慢性を選んでも、鑑別リストに急性のみの病気が出力される。
具体的には、本番環境化の下記データ。
http://symptom-interview.herokuapp.com/interview_sheets/842
主訴：咳・痰
発症様式：1ヶ月以上前→慢性

鑑別リストには、かぜ症候群はでてこないはずだが、一番上に可能性として出ている。

**Comment by makitokezuka** [comment]
744 行目で@onset=nilになっていたことが原因だったので、@2kai　さんの方で修正対応お願いします。

**Comment by mcf-nikai** [comment]
#126修正もろもろのデグレでした。
セッションに保存するようにしました。
ご確認宜しくお願いします。

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
