### ISSUE TITLE
鑑別リストに病気を手動で追加した場合、可能性の低い病気にしかなり得ないので手当が必要

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#246]
鑑別リストに病気を手動で追加した場合、可能性の低い病気にしかなり得ないので手当が必要。
可能性の高いリストの一番上に列挙するようにする

**Comment by makitokezuka** [comment]
こちら、4/7に大久保先生よりも同じ指摘を受けました。
要望としては下記のとおりです。
＜病気を手動で追加した場合＞
・可能性の高い病気、のリストの最後に追加する。
・手動で追加したことが、なんらかでわかる。→例えば、％のところを手動追加、と記載してはどうでしょうか？あわせて、色を変える、等。
・手動で追加したものは、推論がチェックされた状態となっている。

**Comment by mcf-nikai** [comment]
・可能性の高い病気、のリストの最後に追加するようにしました。
・背景色を変えて表示し（元から）、事後確率に「手動追加」と表示するようにしました
・手動で追加したものは、推論がチェックされた状態としました
　→但し保存はしないので、そのまま画面遷移するとクリアされる。

**Comment by makitokezuka** [comment]
確認しました。一旦これはCloseしますが、やはりどれを手動追加したのか、のフラグを持つべきだと思われ、画面上も、手動追加したものがどれか？はわかりやすくなっていたほうが良いと思いました。
例）手動追加フラグの表示、文字色の変更、等。
