### ISSUE TITLE
医療機関側の問診詳細画面、および印刷画面に郵便番号を表示する。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#251]
現在、患者の郵便番号は、住所入力支援のためだけに使っているが、データとして保存し、
医療機関側の問診詳細画面、印刷画面にも郵便番号の表記が欲しい。

**Comment by makitokezuka** [comment]
住所の入力支援なので、殆どないとは思うのですが、郵便番号を、たとえば2桁とか3桁とかしかいれなくても、入力画面上は通ってしまう。その後、詳細確認画面にてエラーが出るので、画面入力時にvalidationが必要。

**Comment by mcf-nikai** [comment]
「詳細確認画面にてエラーが出る」というのは、「次へ」をクリックした時という意味ですか？

その他、医療機関側の詳細画面の編集画面に、入力エリアを追加するのが漏れていましたので、修正します。少々お待ちください。

**Comment by makitokezuka** [comment]
エラーが出るのは医療機関側の問診一覧から問診表示をした時です。

**Comment by mcf-nikai** [comment]
ありがとうございます。バリデーションを追加しました。

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
