### ISSUE TITLE
ipad側にて問診完了画面で診察券番号を入力しなくても印刷できてしまう

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#252]
現在、Interview_sheetsテーブルへのデータ格納が、問診完了前だが、運用上、問診完了画面にて医療機関側が、診察券番号を入力する前に、印刷してしまうことがある。

診察券番号が入力されていない場合は、印刷できないようにするか、あるいは、データ保存のタイミングを、医療機関側にて完了（診察券番号まで入れた状態）に変更した方が良い。

**Comment by mcf-nikai** [comment]
印刷できないようにするか、問診一覧画面の検索条件に「診察券番号未入力も含む」のチェックボックスを追加しましょう。

データ保存のタイミングに関しては、受付スタッフ、ipad、ネットワーク等々の問題で画面が閉じた場合、入力したデータが消失するので現状の仕様が良いでしょう。

**Comment by mcf-nikai** [comment]
印刷できないようにしました

**Comment by makitokezuka** [comment]
確認しました。
