### ISSUE TITLE
風邪用追加質問における、「他に飲んでいる薬」の問診詳細画面側の表記がおかしい

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#255]
風邪用追加質問における、「他に飲んでいる薬」には、選択肢としては、あり／なし／未回答、しか無いはずだが、医療機関側の問診詳細画面では、「その他、上記に当てはまるものがない」と表記されており、どれを患者が選んだのか不明。

**Comment by makitokezuka** [comment]
こちらのissueがステータス変更になっていましたが、修正の対応がされていなかったようなのでステータスを元に戻しました。

**Comment by mcf-nikai** [comment]
失礼しました。修正しました。

また、タイトルの文言が患者画面と医者画面で異なっていたので、患者画面に合わせました。
「他に飲んでいる薬」→「現在飲んでいる薬」

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
