### ISSUE TITLE
長期間使わないとログイン後エラーになる

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#257]
#221 の実装中によるデバッグコード混在していました。

画面のリフレッシュの為に最新の問診データ（interview_sheetsテーブル）のupdated_atを参照していますが、問診データは長期間使うと膨大に溜まっていくので、「日付でソートした先頭」を取得するのではなく、「3日以内のデータをソートした先頭」を取得しているため、長期間使わないとデータが取得できず、デバッグコードが表題の動作不良を起こしていました。

まず、データが取得できずともエラーにならないようにし、
さらに期間は10日以内位がよいかな。

**Comment by makitokezuka** [comment]
確認できる環境がなかったので、確認できていませんがコード確認しました。
