### ISSUE TITLE
ヘッダおよびフッダ部分に　「powered by おおくぼ総合内科」と入れる。

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#259]
ヘッダ部分は、アイコンの横。
フッタ部分は、@2017 media contents factory / okubo medical clinicとする。
なお、ipad側の画面の問診開始画面の説明文の最後に「おおくぼ総合内科」と入れる。

**Comment by mcf-nikai** [comment]
●ヘッダ
バランスを良い感じにするのが難しかったのと、
鑑別機能等の導入によりメニューが増えてくるので、スペースが勿体ないので、
アイコン画像内に文字を入れ込みました。

●フッタ
大久保総合内科クリニックのWEBサイトが大文字で書かれていたので、大文字で。

●問診ウィザード
データ利用の許諾なのでMCFもいるのでは？？
「Media Content Factory / おおくぼ総合内科」にしています。

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
