### ISSUE TITLE
問診画面機能の実装

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#34]
患者側問診画面（タブレット向け画面）のデザイン及び実装

- [x] 問診画面デザイン
- [x] 画面遷移実装
- [x] 実績データの投入実装

**Comment by masoo** [comment]
### slack のまとめ
* 画面１までは病院側が操作
* 将来的に電子カルテ等と連動する場合に、患者IDがキーとなるため画面１で、もし既に診察券を持っている（最新、あるいは初診でもカルテ有り）の場合は病院側にて患者IDを入力させるようにしている
* 初診の場合、まだ診察券番号が決まらないうちに問診に進んだ場合、空欄でそのまま進み、最後の８確認画面で、問診を終了する
* 再診等の場合、画面３で住所と電話番号の入力がいらないけれど、初診でも再診でも、画面３＿基本情報登録の画面で、患者自身が間違えを防ぐためにも、名前、生年月日、性別はいれるようにする
* 
新患の時点で、患者レコードを患者ID自動採番で作成してしまい、再診等の場合は、診察券番号で患者テーブルを検索する、という形式
