### ISSUE TITLE
診断リストに病気追加する機能の実装

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#63]
disease_register_viewとして、daignosis_list_controllerに作成。
・変数としてinterview_sheet_id,及び症状リストを送るので、その対象の病気リストを全て出す。
・ただし、既に登録されている病気はグレーアウト
・病名、病気分類、カテゴライズ、発症様式、で検索絞込可能

**Comment by mcf-nikai** [comment]
症状から想定される対象の病気リストは、問診時に全て登録されていると思いますので、ご確認お願いします。

**Comment by makitokezuka** [comment]
鑑別リストのリストアップとしては、カテゴライズと紐づく病気（categorise_disease_relation)としてリストアップしていますが、このボタンの役割としては、そのヒモ付で漏れている病気があった場合に医師が病気を追加した上で、実際の病気の可能性としてチェックするような導線をイメージしています。

**Comment by mcf-nikai** [comment]
それでは、症状リストをベースとした対象の病気リストではなく、「病気一覧」のように単純に病気を検索して登録できるイメージでOKですか？

**Comment by makitokezuka** [comment]
はい、全ての病気、です。ただし、すでに鑑別リストにある病気はグレーアウト等してほしいです。二重で登録されないように。

**Comment by makitokezuka** [comment]
確認しました。OKです。
