### ISSUE TITLE
発熱用画面及び項目の作成

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#85]
- [x] 発熱用新規画面（症状で発熱を選んだ場合）作成

- [x] 発熱用新規項目 add_column to new table?

- [x] Interview_Sheet_show側実装

**Comment by makitokezuka** [comment]
画面のイメージを下記に記載しました。
画面遷移、および「発熱詳細回答画面」となります。
https://cacoo.com/diagrams/sGUmsKevfa3S1rF2/edit?sid=0B056

**Comment by mcf-nikai** [comment]
症状期間回答画面の後の急性・慢性判断後の矢印を変えました（下図の赤枠内）。
急性の場合鑑別質問に飛ばずに、全て「発熱があるか？」の判断を通るようにしました。
この方向で実装中ですので、もし間違った修正であればご指摘ください。

![default](https://cloud.githubusercontent.com/assets/24665918/22725742/aab34cda-ee12-11e6-9b24-f2a056235cb3.png)

**Comment by makitokezuka** [comment]
発熱が主訴の場合（カテゴライズでいうと、1週間以上続く発熱、など）データ格納が下記となっている。
```
[4] pry(#<MedicalInterviewStepsController>)> @symptom_ids
=> [1002, "1017"]
```
その為、画面を表示する下記条件を通らない。
(medical_interview_step_controller 400行目)
```
      if @symptom_ids.include?(SYMPTOM_ID_FERVER.to_s)
        if !(param_validate(params_key: :ferver_pattern, message: "発熱の経過を選んでください"))
          params.delete(:to_discrimination_question)
          params[:to_fever_detail] = "to_fever_detail"
        end
```

あと、388行目の方も通らないけど、ここは関係ない？

そもそものデータ格納が主訴と随伴症状で食い違ってしまっているのは、私が原因なので大変申し訳無いのですが、、、他に影響していたりしないだろうかと心配になっっています。

**Comment by makitokezuka** [comment]
確認しました。ありがとうございます。
