### ISSUE TITLE
完了画面から、患者問診回答内容を確認する画面を作成

### ISSUE THREAD

**Issue by makitokezuka** [makitokezuka/symptom-interview#88]

**Comment by mcf-nikai** [comment]
下記の画面で回答内容を確認できるようにしたい。という理解で合っていますか？

![default](https://cloud.githubusercontent.com/assets/24665918/22090239/c3d736fc-de33-11e6-9e8c-2a165fc08b91.png)

**Comment by makitokezuka** [comment]
はい、あっています。イメージとしては、この画面に問診内容確認等のボタンをつけて、内容の確認イメージとしては、confirmation（確認画面）viewのレイアウトで表示されるイメージです。

**Comment by mcf-nikai** [comment]
「回答内容確認」ボタンを配置して、ボタンクリックで画面下部に回答内容を読み取り専用で表示するようにしました。
![default](https://cloud.githubusercontent.com/assets/24665918/22133861/378e8f78-df06-11e6-8e56-0501c18df1f9.png)

**Comment by makitokezuka** [comment]
OKです。

**Comment by makitokezuka** [comment]
@mcf-nikai 上記でOKです。一応ipadでの操作に不自由ないか、テスト願います。

**Comment by mcf-nikai** [comment]
確認しました。OKと思います。
