### ISSUE TITLE
病気や症状のデータについて

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#95]
病気や症状の詳細画面において、編集モードになっていますが必要でしょうか？
（あるいはα版の今だけ？）
病院が編集できてしまうと、他の病院へも影響してしまうか、もしくは病気や症状のデータを「病院単位」に持つ必要が出てくると思います。
「最初にデータを作る（作ってもらう）ため」であれば、WEB画面よりも、EXCEL等の方が良い事ないでしょうか？
（企業相手だとEXCELが好まれるので。。。）

**Comment by makitokezuka** [comment]
@mcf-nikai 　α版だけ、というイメージです。とりあえず最初に試してもらう医療機関（大久保総合内科）は一緒にデータの点数とかを決めてきたので、α版で試しつつ、数値を少しいじることがあり得ると考えたためです。 基本的には基本的な点数は、一律で持っておき、病院単位では、「病気の出現確率の調整数値」的なロジックを将来　的には実装しようとおもっています

**Comment by mcf-nikai** [comment]
了解です。クローズします。
