### ISSUE TITLE
問診画面で[戻る]ボタンをクリックすると「Web ページの有効期限が切れています」エラーになる

### ISSUE THREAD

**Issue by mcf-nikai** [makitokezuka/symptom-interview#96]
問診画面で[戻る]ボタンをクリックすると「Web ページの有効期限が切れています」エラーになる

**Comment by makitokezuka** [comment]
@mcf-nikai これ、なんでおきるんですかね。。。出現条件がよくわかっておらず。

**Comment by mcf-nikai** [comment]
問診終了画面で、ブラウザで戻ると進むを繰り返すと、どんどんごみデータが出来ていくので、ちょっと考えた方が良いかもしれません。

**Comment by mcf-nikai** [comment]
以下修正しました。

- TOPページ（2回目から問診終了ページへ戻れるので）と、問診終了ページで[戻る]を無効に。

- 問診終了ページでリロードした時に再度Insert処理が走らないように。

以下備忘録
ページの有効期限切れについては、開発中にセッション上書きとか消去とかした可能性あり。
様子見。
-----------------------------------------------------------------------------------------------------
　セッションの有効期限は0（セッションクッキー：ブラウザ閉じるまで）
　httpヘッダ：
　　Cache-Control:max-age=0, private, must-revalidate
　　　　（キャッシュの有効性について必ず毎回サーバに問い合せを行う）
　　Expire（コンテンツ有効期限）→出していない
　　ETag有り（コンテンツのGUID→コンテンツファイルのチェックサム）

**Comment by makitokezuka** [comment]
1/30 毛塚にてテスト。一通り戻るボタンをいろんな画面で押してみて現象再現はしないので、Close
